from settings import ROLE_MASTER_BOOSTER_ID, ROLE_ELITE_BOOSTER_ID, ROLE_VETERAN_BOOSTER_ID, ROLE_GOLD_BOOSTER_ID, ROLE_BOOSTER_ID, ROLE_DEVELOPER_ID

def give_all_booster_roles(): 
    return f'<@&{ROLE_MASTER_BOOSTER_ID}> <@&{ROLE_ELITE_BOOSTER_ID}> <@&{ROLE_VETERAN_BOOSTER_ID}> <@&{ROLE_GOLD_BOOSTER_ID}> <@&{ROLE_BOOSTER_ID}>'
